### ISSUE TITLE
BUG: destinationFileName is ignored

### ISSUE THREAD

**Issue by nkitsaini** [Cleveroad/cr_file_saver#7]
While saving the file using `saveFileWithDialog`,  `destinationFileName` is not used.

https://github.com/Cleveroad/cr_file_saver/blob/main/android/src/main/kotlin/com/cleveroad/cr_file_saver/CrFileSaverPlugin.kt#L87

**Comment by ivanmyzherytskyi** [comment]
Hi, thanks for the opened issue!

We fixed this in new update 0.0.2+1 https://pub.dev/packages/cr_file_saver/changelog.
